using DoxFrame.Hub.Core.ProjectAggregate;
using System;
using System.ComponentModel.DataAnnotations;

namespace DoxFrame.Hub.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class FormDTO : UpdateFormDTO 
    {
        public Guid Id { get; set; }
        [Required]
        public string Title { get; set; }
        public static FormDTO FromToForm(Form form)
        {
            return new FormDTO()
            {
                Id = form.Id,
                Title= form.Title,
                Description = form.Description,
                IsPublished = form.isPublished
            };
        }
    }
    // Creation DTOs should not include an ID if the ID will be generated by the back end
   
    public class UpdateFormDTO
    {
        public Guid ProjectId { get; set; }
        public string FormKey { get; set; }
        public string Description { get; set; }
        public string OperationType { get; set; }
        public string RequestMethod { get; set; }
        public string RequestUri { get; set; }
        public bool IsPublished { get; set; }
        public bool IsActive { get; set; }


    }
    public class RemoveFormDTO { 
        public Guid ProjectId { get; set; }
        public Guid FormId { get; set; }
    }
    public class UpdateFormLayoutDTO
    {
        public Guid ProjectId { get; set; }
        public Guid FormId { get; set; }
        public string Layout { get; set; }
    }
}
