using System;
using System.Collections.Generic;

namespace DoxFrame.Hub.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class HubUserDTO : CreateHubUserDTO
    {
        public Guid Id { get; set; }

    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateHubUserDTO
    {
        public string AuthUserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Type { get; set; }
        public bool IsAccountAdmin { get; set; }

      


    }
}
