using System;
using System.Collections.Generic;

namespace DoxFrame.Hub.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class ProjectDTO : CreateProjectDTO
    {
        public Guid Id { get; set; }
        public List<FormDTO> Forms = new();
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateProjectDTO
    {
        public Guid HubUserId { get; set; }
        public Guid TenantId { get; set; }
        public string ProjectName { get; set; }
        public string Summary { get; set; }
    }
    public class RemoveProjectDTO
    {
        public Guid TenantId { get; set; }
        public Guid ProjectId { get; set; }
    }
}
