using DoxFrame.Hub.Core.ProjectAggregate;
using System;
using System.ComponentModel.DataAnnotations;

namespace DoxFrame.Hub.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class WorkflowsDTO : UpdateProcessDTO 
    {
        public Guid Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Name { get; set; }

        public static WorkflowsDTO FromToProcess(Workflow process)
        {
            return new WorkflowsDTO()
            {
                Id = process.Id,
                Title= process.Title,
                Name = process.Name,
            };
        }
    }
    // Creation DTOs should not include an ID if the ID will be generated by the back end
   
    public class UpdateProcessDTO
    {
        public Guid ProjectId { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }

    }
    public class RemoveWorkflowDTO { 
        public Guid ProjectId { get; set; }
        public Guid WorkflowId { get; set; }
    }

    public class UpdateWorkflowModelLayoutDTO
    {
        public Guid ProjectId { get; set; }
        public Guid WorkflowId { get; set; }
        public string Layout { get; set; }
    }

}
