using System;
using System.Collections.Generic;

namespace DoxFrame.Hub.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class TenantDTO : CreateTenantDTO
    {
        public Guid Id { get; set; }

    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateTenantDTO
    {
        public Guid HubUserId { get; set; }
        public string DomainName { get; set; }
        public string Region { get; set; }
        public string EnvironmentTag { get; set; } // Dev, Stag, Prod


    }
}
